### ISSUE TITLE
Simplify per-Action Check()s

### ISSUE THREAD

**Issue by fenollp** [flyingmutant/rapid#10]
Right now `rapid.T` does not provide a way to differentiate what the previously run action was.
Because of this one has to resort to some hopeful (and maybe thread-safe) logic in their own `(*Model).Check(*rapid.T)`.

How about creating a `rapid.M` that embeds `rapid.T` and additionally provides a `(*rapid.M).LastAction()A` where `A` represents the last action that was run or some empty value for the first step/check (I'm not clear on the step-check relationship just yet: checks have steps? or is it the other way around?).
`A` could be `string` but if possible it could be a pointer to `*Model`'s method.

**Comment by flyingmutant** [comment]
Can you please explain the use case where the last action is important?

P.S. All actions and checks are of course [run in a single thread](https://github.com/flyingmutant/rapid/blob/master/statemachine.go#L67-L75).

**Comment by flyingmutant** [comment]
Also, `Check()` is "global" by design; for "per-action" check, you simply test the condition inside the action itself (calling e.g. `t.Fatalf()` if appropriate).

**Comment by fenollp** [comment]
Oh you're right. I hadn't thought of it this way (coming from other QC libs).
Yeah I guess there is no point in differentiating between a failed action and a failed check on this action. None that I can think of right now anyway.

Thanks!

**Comment by flyingmutant** [comment]
Yeah, the API turned out to be a bit unusual indeed! Hope it is a decent one in the end :-)
