### ISSUE TITLE
A case for the state machine interface

### ISSUE THREAD

**Issue by fenollp** [flyingmutant/rapid#11]
Right now there is no
```go
type StateMachine interface {
	Init(*T)
	Check(*T)
	Cleanup()
}
```
I think these should really be mandatory (at least the first 2, but the implementation for no-op `(*Model)Cleanup()` is a one liner).

* it would show up better in documentation
* one could ensure they're doing it right with `var _ rapid.StateMachine = (*Model)(nil)`
* it could save a bit of processing (not doing reflection on these)
* `Cleanup()` could be split into its own single method interface and reflection usage replaced with a `_, ok := x.(Cleanuper); ok` check

**Comment by flyingmutant** [comment]
This definitely sounds interesting. The question is how big the interface should be, maybe just
```go
type StateMachine interface {
        Check(*T)
}
```
is enough? `StateMachine()` can be then renamed to `Run()` which is both more concise and precise.

**Comment by fenollp** [comment]
Yeah intf can have just one method. 
I preferred StateMachine over Run for its meaning though but you’re the boss :)
