### ISSUE TITLE
Allow set startSeed from lib api

### ISSUE THREAD

**Issue by flaviostutz** [flyingmutant/rapid#14]
Expose in API the startSeed variable so that the test algorithm itself can set this parameters. Today this is possible only by a command line argument.

I tried to pass this parameter to my tests with "go test -args rapid.seed=999" and it works only when all tests needs rapid. When we have various tests mixed with tests that don't need "rapid", it fails because the test binary receives an "unsupported" argument (because flag on those binaries doesn't need this argument).

**Comment by flyingmutant** [comment]
Can you please explain why do you want to fix the seed when running tests? It was only intended for reproducing the failures during debugging, doing so for regular test runs seem counter-productive to me.

**Comment by flaviostutz** [comment]
After accepting a PR with some “passed” unit tests, we would like to have those tests always returning the same results from build to build. We had some issues with new PR coming and new errors showed up because a random condition did not pass a test for a component that was already approved in a previous PR (in this case the \r\n bug was in a URL field that would not even have this condition in a practical condition).

We would like to have our unit tests repeatable so that we would know that new errors are really the responsibility of who last changed the code.
 
We do have separate “brute force” fuzzy tests with random values in our continuous integration pipeline in order to cover this scenario of “brute frute diversity”, but would like to have our unit tests more stable.

**Comment by flyingmutant** [comment]
That's the whole point of using rapid (or any other decent property-based testing system), though: having tests that are always exploring state space for possible violations of the properties, and not merely re-running the checks that are known to pass.

I don't like the idea of having an API which makes property-based testing much less useful. If you absolutely require having 100% repeatable tests, you can use `(*testing.T).Skip()` to only run rapid tests conditionally -- but I would personally advice against that.
