### ISSUE TITLE
Shrink regex-generated strings

### ISSUE THREAD

**Issue by mtaran** [flyingmutant/rapid#29]
Currently it doesn't seem like shrinking is applied to regex-generated strings. This would be very useful in a lot of cases (though not so much in e.g. the IPv4 example). Or is shrinking done for those already? I couldn't find a shrunken output in my testing, only a very long example.

**Comment by flyingmutant** [comment]
Hm, that's strange. There are no exceptions, the same (simple) shrinking is used for everything. Can you provide an example where rapid fails to properly shrink regexp-generated string?
