### ISSUE TITLE
Should update go.mod's name

### ISSUE THREAD

**Issue by atlas-comstock** [flyingmutant/rapid#33]
```
$  GO111MODULE=on go get  github.com/flyingmutant/rapid


go get: github.com/flyingmutant/rapid@v0.4.7: parsing go.mod:
        module declares its path as: pgregory.net/rapid
                but was required as: github.com/flyingmutant/rapid
```

**Comment by flyingmutant** [comment]
Import path was changed from `github.com/flyingmutant/rapid` to `pgregory.net/rapid` some time ago. Please update your code to use the new one.

**Comment by atlas-comstock** [comment]
OK, but it is strange that import name does not match the github name, which we use to `go get` usually.

**Comment by flyingmutant** [comment]
Yes, it is common for import path to match github path, but it is not required. You can check [go.mod](https://github.com/flyingmutant/rapid/blob/master/go.mod) to see the correct one.
