### ISSUE TITLE
statemachine cleanup method argument

### ISSUE THREAD

**Issue by meridional** [flyingmutant/rapid#34]
Right now, statemachine's cleanup method is of type `func()` instead of `func(*testing.T)`.

It might be too late to change the function signature, but it might be worth to support both?

One use case is that we can use `Init` to test the "constructors" of a data structure, and use `Cleanup` to test the "destructors".

**Comment by flyingmutant** [comment]
Did you mean `Cleanup(t *rapid.T)`? Can you please tell a bit more about the test you want to construct?

**Comment by flyingmutant** [comment]
Related: #49.
