### ISSUE TITLE
Feature request : Tags for reporting distribution of generated data sets

### ISSUE THREAD

**Issue by ashishnegi** [flyingmutant/rapid#51]
Hey Folks

In real world complex scenarios, visualizing the buckets in which generated input is falling helps debug/improve the generators.
I did not find this functionality in library.

Please see similar feature in [cpp rapidcheck library document](https://github.com/emil-e/rapidcheck/blob/master/doc/distribution.md).

Example: User generator with name, sex, date of birth can add tags like `male/female` for sex, `child/adult/old` for age.

After running test, distribution will show the buckets and will help identify if there is any mistake in generator or if we are generating domain-interesting inputs or not. This is very useful for real world scenarios.

**Comment by flyingmutant** [comment]
There is already an existing issue, let's keep the discussion there: #30 (and a WIP PR #31).
