### ISSUE TITLE
Consider adding a comparison section to the README

### ISSUE THREAD

**Issue by flyingmutant** [flyingmutant/rapid#55]
Old one: [link](https://github.com/flyingmutant/rapid/tree/26f3bd5a978f9f8dfd458a3022b5aa23498ace52#comparison). Maybe expand it and add a comparison to built-in fuzzing as well.

**Comment by gedw99** [comment]
https://github.com/gotestyourself is another one that tends to lean towards file based testing .

it als has goldens for comparing tests over time.

It’s also got a watcher to run tests again when files change.

**Comment by gedw99** [comment]
Are you trying to make a golang equivalent of Hypothesis?

**Comment by flyingmutant** [comment]
Hypothesis was the original inspiration for creating rapid. The goal is not to create a direct equivalent, rather, try to give Go users a tool of similar power and convenience.

**Comment by dtjm** [comment]
How does this package compare to `testing/quick`?

**Comment by flyingmutant** [comment]
> How does this package compare to `testing/quick`?

Please see https://github.com/flyingmutant/rapid#comparison.
