### ISSUE TITLE
Tests failed on go-1.21

### ISSUE THREAD

**Issue by Hellseher** [flyingmutant/rapid#68]
Hi,

During refreshing package in Guix I've faced with an issue when `rapid` starts
experiencing unit tests failure when compiling with go-1.21, please see the
trace:
![Screenshot from 2024-07-20 20-17-37](https://github.com/user-attachments/assets/a0619837-9213-4d8b-8018-0c987ff5a455)

```
--- FAIL: ExampleRune (0.00s)
got:
'\n' '\x1b' 'A' 'a' '*'
'0' '@' '?' '\'' '\ue05d'
'<' '%' '!' '\u0604' 'A'
'%' '╷' '~' '!' '/'
'\u00ad' '𝅾' '@' '҈' ' '
want:
'\n' '\x1b' 'A' 'a' '*'
'0' '@' '?' '\'' '\ue05d'
'<' '%' '!' '\u0604' 'A'
'%' '╷' '~' '!' '/'
'\u00ad' '𝪪' '@' '҈' ' '
--- FAIL: ExampleString (0.00s)
got:
"\n߾⃝?\rA�֍"
"\u2006𑨳"
"A＄\u0603ᾢ"
"+^#.[#৲"
""
want:
"\n߾⃝?\rA�֍"
"\u2006𑰼"
"A￠\u0603ᾢ"
"+^#.[#৲"
""
--- FAIL: ExampleStringN (0.00s)
got:
"\n߾⃝?\r"
"\u2006𑨳#`\x1b"
"A＄\u0603ᾢÉ"
"+^#.["
".A<a¤"
want:
"\n߾⃝?\r"
"\u2006𑰼#`\x1b"
"A￠\u0603ᾢÉ"
"+^#.["
".A<a¤"
FAIL
FAIL    pgregory.net/rapid      1.782s
FAIL
```

Thanks,
Oleg

**Comment by flyingmutant** [comment]
Thanks for reporting! Does this happen on current `master`?

**Comment by Hellseher** [comment]
Hi @flyingmutant 

It's failing on the latest commit as well 3aa554aaca7a7a3e7c671564c95190542db6fcc4, same issue.

**Comment by flyingmutant** [comment]
Full test suite is run daily with several versions of Go and 3 operating systems. [Here](https://github.com/flyingmutant/rapid/actions/runs/10119722479) is one of the runs with the version https://github.com/flyingmutant/rapid/commit/3aa554aaca7a7a3e7c671564c95190542db6fcc4. The problem you are seeing is most likely caused by a custom version of Go (with different Unicode tables) or something of that kind.

**Comment by Hellseher** [comment]
Hi,

Thank you for explanation. 

Which Go version (commit or build type) is used to run the tests in the CI? I'd
try to reproduce it.

It might be this: https://launchpad.net/ubuntu/+source/golang-1.21
I tried to build with https://github.com/golang/go/tree/go1.21.5

Oleg.

**Comment by flyingmutant** [comment]
From the action I've linked:

```
Setup go stable version spec 1.21
Found in cache @ /opt/hostedtoolcache/go/1.21.12/x64
Added go to the path
Successfully setup go version 1.21
go version go1.21.12 linux/amd64
```
