### ISSUE TITLE
Log interface that only outputs the final run

### ISSUE THREAD

**Issue by james-w** [flyingmutant/rapid#73]
Hi,

I'm not totally sure about how this works, so if I missed something I apologise.

It looks that if the test log interface is used during the test (`rapid.T.Log` etc), then all of the messages are logged.

This makes the output quite hard to understand as rapid goes through iterations, shrinking etc.

Other similar libraries I've used in other languages had a way to log messages such that they were suppressed if it wasn't the final run. This meant that when you got a failure you saw all the log messages related to that failure, and not any from other iterations. This is particular important if there are tests that output a lot, and with many iterations.

A workaround is to log a "start iteration" or similar message in the test so that you can ignore anything prior to that.

I'm finding rapid to be far superior to the other property testing I've done in Go previously though, so thanks for working on it!

**Comment by flyingmutant** [comment]
Hi, thanks for the kind words. Can you post a reproducer of the issue? Rapid should always do what you expected (unless `-rapid.log` command-line flag was specified).

**Comment by james-w** [comment]
Hi, indeed it does. I was getting confused as I also had ginkgo in the mix, and was bypassing `rapid.T.log` with calls to `By`. I've dropped Ginkgo and I see that it works as I expect.Sorry for the noise!
